### ISSUE TITLE
API stabilization towards 1.0

### ISSUE THREAD

**Issue by minad** [judofyr/temple#87]
Hi,

I would like to release a version 1.0 at some point. For that reason I am looking if there are some problematic parts in temple that require change. I am aware of the following (more or less active) engines using temple:
- https://github.com/slim-template/slim @minad
- https://github.com/k0kubun/hamlit @k0kubun
- https://github.com/eagletmt/faml @eagletmt
- https://github.com/blambeau/wlang @blambeau
- https://github.com/shelling/huml @shelling
- https://github.com/rehab/rehab @rehab
- https://github.com/stonean/sal.rb @stonean 

Please make suggestions for improvements!

**Comment by blambeau** [comment]
As far as `wlang` is concerned, everything is fine. No temple-related issues at all.

**Comment by minad** [comment]
Any suggestions for missing features, API improvements which would help your project?

**Comment by blambeau** [comment]
Well, `wlang` only uses the main compiler infrastructure, (almost no filter) and no generator from temple. (I've even considered removing temple as a dependency, but did not so far, and will probably never). For my use case, temple is just OK, but that's an easy use case...

The reason no generator is used is that wlang is very dynamic in nature: it actually delegates many decisions at runtime, because of the so-called dialects (wlang is not a templating language, it is a meta thing). That kills the ability to use temple's generators. I don't thing it is worth considering temple improvements along those lines, because it is very specific to wlang.

For the rest it's been a long time since I hacked the temple/wlang core, so possibly I don't remember.

**Comment by minad** [comment]
@blambeau thx for your explanation and feedback!

**Comment by minad** [comment]
Remember #88, better documentation!

**Comment by k0kubun** [comment]
For hamlit, everything is fine too. But I want to say 2 points I felt not so flexible during developing hamlit.

I want to use sexp whose name includes underscore. In other words, I want `Temple::Filter`'s `on_foo_bar` to catch not only `[:foo, :bar]` but also `[:foo_bar]`. Maybe it is not easy to change.

I thought `Temple::Engine` should provide some API to write [this](https://github.com/slim-template/slim/blob/efaa090066c3bc2a8b0db48f4c296271148bc1e8/lib/slim/engine.rb#L38) more easily. It will be `valid_options_for` or just `options_for`, etc.

**Comment by minad** [comment]
@k0kubun thx for your feedback. Your point about underscore sexps, is this only because of esthetics? Temple doesn't allow underscored names for the sexp names.

I agree with your second point about the engine chain construction. This is too complicated as it is done now. Depending on the argument different constructors are selected, take a look at EngineDSL. I would like to make that maybe a bit more explicit and intuitive. Do you have suggestions?

Any filters that you think were missing?

**Comment by k0kubun** [comment]
My first point is not so serious. Never mind!

I wrote code to show my second point's idea in https://github.com/judofyr/temple/pull/89.
